// Code generated by tommy 0.4.1 (bce2bf3); DO NOT EDIT.

package schema

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type corpusConfigHandle struct {
	node *cst.Node
}
type ManeaterConfigDocument struct {
	data    ManeaterConfig
	cstDoc  *document.Document
	model   *cst.Value
	corpora []corpusConfigHandle
}

func DecodeManeaterConfig(input []byte) (*ManeaterConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &ManeaterConfigDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vDefault, _ok := model.Get("default"); _ok && _vDefault.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDefault.Leaf); _xok {
			d.data.Default = _x
			_vDefault.MarkConsumed()
		}
	}
	if _vModels, _ok := model.Get("models"); _ok && _vModels.Kind == cst.VTable {
		_vModels.MarkSeen()
		d.data.Models = make(map[string]ModelConfig)
		for _mk0i := range _vModels.Fields {
			_mk0e := &_vModels.Fields[_mk0i]
			if _mk0e.Val.Kind == cst.VTable {
				_mk0e.Val.MarkSeen()
				var entry1 ModelConfig
				if _vModelsPath, _ok := _mk0e.Val.Get("path"); _ok && _vModelsPath.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vModelsPath.Leaf); _xok {
						entry1.Path = _x
						_vModelsPath.MarkConsumed()
					}
				}
				if _vModelsQueryPrefix, _ok := _mk0e.Val.Get("query-prefix"); _ok && _vModelsQueryPrefix.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vModelsQueryPrefix.Leaf); _xok {
						entry1.QueryPrefix = _x
						_vModelsQueryPrefix.MarkConsumed()
					}
				}
				if _vModelsDocumentPrefix, _ok := _mk0e.Val.Get("document-prefix"); _ok && _vModelsDocumentPrefix.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vModelsDocumentPrefix.Leaf); _xok {
						entry1.DocumentPrefix = _x
						_vModelsDocumentPrefix.MarkConsumed()
					}
				}
				if _vModelsNCtx, _ok := _mk0e.Val.Get("n-ctx"); _ok && _vModelsNCtx.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractInt(_vModelsNCtx.Leaf); _xok {
						entry1.NCtx = _x
						_vModelsNCtx.MarkConsumed()
					}
				}
				if _vModelsPooling, _ok := _mk0e.Val.Get("pooling"); _ok && _vModelsPooling.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vModelsPooling.Leaf); _xok {
						entry1.Pooling = _x
						_vModelsPooling.MarkConsumed()
					}
				}
				if _vModelsTruncate, _ok := _mk0e.Val.Get("truncate"); _ok && _vModelsTruncate.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vModelsTruncate.Leaf); _xok {
						entry1.Truncate = _x
						_vModelsTruncate.MarkConsumed()
					}
				}
				d.data.Models[_mk0e.Key] = entry1
			}
		}
	}
	if _vManpath, _ok := model.Get("manpath"); _ok && _vManpath.Kind == cst.VTable {
		_vManpath.MarkSeen()
		manpathVal2 := &ManpathConfig{}
		if _vManpathInclude, _ok := _vManpath.Get("include"); _ok && _vManpathInclude.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vManpathInclude.Leaf); _xok {
				manpathVal2.Include = _x
				if manpathVal2.Include == nil {
					manpathVal2.Include = []string{}
				}
				_vManpathInclude.MarkConsumed()
			}
		}
		if _vManpathNoAuto, _ok := _vManpath.Get("no-auto"); _ok && _vManpathNoAuto.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vManpathNoAuto.Leaf); _xok {
				manpathVal2.NoAuto = _x
				_vManpathNoAuto.MarkConsumed()
			}
		}
		d.data.Manpath = manpathVal2
	} else {
		manpathVal2 := &ManpathConfig{}
		_foundManpath := false
		if _vInclude, _ok := model.Get("include"); _ok && _vInclude.Kind == cst.VLeaf {
			_foundManpath = true
			if _x, _xok := cst.ExtractStringSlice(_vInclude.Leaf); _xok {
				manpathVal2.Include = _x
				if manpathVal2.Include == nil {
					manpathVal2.Include = []string{}
				}
				_vInclude.MarkConsumed()
			}
		}
		if _vNoAuto, _ok := model.Get("no-auto"); _ok && _vNoAuto.Kind == cst.VLeaf {
			_foundManpath = true
			if _x, _xok := cst.ExtractBool(_vNoAuto.Leaf); _xok {
				manpathVal2.NoAuto = _x
				_vNoAuto.MarkConsumed()
			}
		}
		if _foundManpath {
			d.data.Manpath = manpathVal2
		}
	}
	if _vStorage, _ok := model.Get("storage"); _ok && _vStorage.Kind == cst.VTable {
		_vStorage.MarkSeen()
		storageVal3 := &StorageConfig{}
		if _vStorageStoreId, _ok := _vStorage.Get("store-id"); _ok && _vStorageStoreId.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vStorageStoreId.Leaf); _xok {
				storageVal3.StoreID = _x
				_vStorageStoreId.MarkConsumed()
			}
		}
		if _vStorageReadCmd, _ok := _vStorage.Get("read-cmd"); _ok && _vStorageReadCmd.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vStorageReadCmd.Leaf); _xok {
				storageVal3.ReadCmd = _x
				if storageVal3.ReadCmd == nil {
					storageVal3.ReadCmd = []string{}
				}
				_vStorageReadCmd.MarkConsumed()
			}
		}
		if _vStorageWriteCmd, _ok := _vStorage.Get("write-cmd"); _ok && _vStorageWriteCmd.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vStorageWriteCmd.Leaf); _xok {
				storageVal3.WriteCmd = _x
				if storageVal3.WriteCmd == nil {
					storageVal3.WriteCmd = []string{}
				}
				_vStorageWriteCmd.MarkConsumed()
			}
		}
		if _vStorageExistsCmd, _ok := _vStorage.Get("exists-cmd"); _ok && _vStorageExistsCmd.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vStorageExistsCmd.Leaf); _xok {
				storageVal3.ExistsCmd = _x
				if storageVal3.ExistsCmd == nil {
					storageVal3.ExistsCmd = []string{}
				}
				_vStorageExistsCmd.MarkConsumed()
			}
		}
		if _vStorageInitCmd, _ok := _vStorage.Get("init-cmd"); _ok && _vStorageInitCmd.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vStorageInitCmd.Leaf); _xok {
				storageVal3.InitCmd = _x
				if storageVal3.InitCmd == nil {
					storageVal3.InitCmd = []string{}
				}
				_vStorageInitCmd.MarkConsumed()
			}
		}
		d.data.Storage = storageVal3
	} else {
		storageVal3 := &StorageConfig{}
		_foundStorage := false
		if _vStoreId, _ok := model.Get("store-id"); _ok && _vStoreId.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractString(_vStoreId.Leaf); _xok {
				storageVal3.StoreID = _x
				_vStoreId.MarkConsumed()
			}
		}
		if _vReadCmd, _ok := model.Get("read-cmd"); _ok && _vReadCmd.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractStringSlice(_vReadCmd.Leaf); _xok {
				storageVal3.ReadCmd = _x
				if storageVal3.ReadCmd == nil {
					storageVal3.ReadCmd = []string{}
				}
				_vReadCmd.MarkConsumed()
			}
		}
		if _vWriteCmd, _ok := model.Get("write-cmd"); _ok && _vWriteCmd.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractStringSlice(_vWriteCmd.Leaf); _xok {
				storageVal3.WriteCmd = _x
				if storageVal3.WriteCmd == nil {
					storageVal3.WriteCmd = []string{}
				}
				_vWriteCmd.MarkConsumed()
			}
		}
		if _vExistsCmd, _ok := model.Get("exists-cmd"); _ok && _vExistsCmd.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractStringSlice(_vExistsCmd.Leaf); _xok {
				storageVal3.ExistsCmd = _x
				if storageVal3.ExistsCmd == nil {
					storageVal3.ExistsCmd = []string{}
				}
				_vExistsCmd.MarkConsumed()
			}
		}
		if _vInitCmd, _ok := model.Get("init-cmd"); _ok && _vInitCmd.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractStringSlice(_vInitCmd.Leaf); _xok {
				storageVal3.InitCmd = _x
				if storageVal3.InitCmd == nil {
					storageVal3.InitCmd = []string{}
				}
				_vInitCmd.MarkConsumed()
			}
		}
		if _foundStorage {
			d.data.Storage = storageVal3
		}
	}
	if _vCorpora, _ok := model.Get("corpora"); _ok && _vCorpora.Kind == cst.VArray {
		_vCorpora.MarkSeen()
		d.data.Corpora = make([]CorpusConfig, len(_vCorpora.Items))
		d.corpora = make([]corpusConfigHandle, len(_vCorpora.Items))
		for i := range _vCorpora.Items {
			_eCorpora := &_vCorpora.Items[i]
			_eCorpora.MarkSeen()
			d.corpora[i] = corpusConfigHandle{node: _eCorpora.Node}
			if _vCorporaName, _ok := _eCorpora.Get("name"); _ok && _vCorporaName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vCorporaName.Leaf); _xok {
					d.data.Corpora[i].Name = _x
					_vCorporaName.MarkConsumed()
				}
			}
			if _vCorporaType, _ok := _eCorpora.Get("type"); _ok && _vCorporaType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vCorporaType.Leaf); _xok {
					d.data.Corpora[i].Type = _x
					_vCorporaType.MarkConsumed()
				}
			}
			if _vCorporaPaths, _ok := _eCorpora.Get("paths"); _ok && _vCorporaPaths.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaPaths.Leaf); _xok {
					d.data.Corpora[i].Paths = _x
					if d.data.Corpora[i].Paths == nil {
						d.data.Corpora[i].Paths = []string{}
					}
					_vCorporaPaths.MarkConsumed()
				}
			}
			if _vCorporaMaxChars, _ok := _eCorpora.Get("max-chars"); _ok && _vCorporaMaxChars.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vCorporaMaxChars.Leaf); _xok {
					d.data.Corpora[i].MaxChars = _x
					_vCorporaMaxChars.MarkConsumed()
				}
			}
			if _vCorporaListCmd, _ok := _eCorpora.Get("list-cmd"); _ok && _vCorporaListCmd.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaListCmd.Leaf); _xok {
					d.data.Corpora[i].ListCmd = _x
					if d.data.Corpora[i].ListCmd == nil {
						d.data.Corpora[i].ListCmd = []string{}
					}
					_vCorporaListCmd.MarkConsumed()
				}
			}
			if _vCorporaReadCmd, _ok := _eCorpora.Get("read-cmd"); _ok && _vCorporaReadCmd.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaReadCmd.Leaf); _xok {
					d.data.Corpora[i].ReadCmd = _x
					if d.data.Corpora[i].ReadCmd == nil {
						d.data.Corpora[i].ReadCmd = []string{}
					}
					_vCorporaReadCmd.MarkConsumed()
				}
			}
			if _vCorporaHashCmd, _ok := _eCorpora.Get("hash-cmd"); _ok && _vCorporaHashCmd.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaHashCmd.Leaf); _xok {
					d.data.Corpora[i].HashCmd = _x
					if d.data.Corpora[i].HashCmd == nil {
						d.data.Corpora[i].HashCmd = []string{}
					}
					_vCorporaHashCmd.MarkConsumed()
				}
			}
			if _vCorporaPrepareCmd, _ok := _eCorpora.Get("prepare-cmd"); _ok && _vCorporaPrepareCmd.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaPrepareCmd.Leaf); _xok {
					d.data.Corpora[i].PrepareCmd = _x
					if d.data.Corpora[i].PrepareCmd == nil {
						d.data.Corpora[i].PrepareCmd = []string{}
					}
					_vCorporaPrepareCmd.MarkConsumed()
				}
			}
			if _vCorporaWorkers, _ok := _eCorpora.Get("workers"); _ok && _vCorporaWorkers.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vCorporaWorkers.Leaf); _xok {
					d.data.Corpora[i].Workers = _x
					_vCorporaWorkers.MarkConsumed()
				}
			}
			if _vCorporaModel, _ok := _eCorpora.Get("model"); _ok && _vCorporaModel.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vCorporaModel.Leaf); _xok {
					d.data.Corpora[i].Model = _x
					_vCorporaModel.MarkConsumed()
				}
			}
		}
	}
	if _eaCorpora, _eaok := model.Get("corpora"); _eaok && _eaCorpora.IsEmptyArray() {
		_eaCorpora.MarkConsumed()
		d.data.Corpora = []CorpusConfig{}
	}
	return d, nil
}

func (d *ManeaterConfigDocument) Data() *ManeaterConfig {
	return &d.data
}

func (d *ManeaterConfigDocument) Encode() ([]byte, error) {
	if d.data.Default != "" || cst.HasValue(d.cstDoc.Root(), "default") {
		if err := cst.SetAny(d.cstDoc.Root(), "default", d.data.Default); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if len(d.data.Models) > 0 {
		for mapKey, mapVal := range d.data.Models {
			subTable := cst.EnsureChildSubTable(d.cstDoc.Root(), d.cstDoc.Root(), "models", mapKey)
			if mapVal.Path != "" || cst.HasValue(subTable, "path") {
				if err := cst.SetAny(subTable, "path", mapVal.Path); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if mapVal.QueryPrefix != "" || cst.HasValue(subTable, "query-prefix") {
				if err := cst.SetAny(subTable, "query-prefix", mapVal.QueryPrefix); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if mapVal.DocumentPrefix != "" || cst.HasValue(subTable, "document-prefix") {
				if err := cst.SetAny(subTable, "document-prefix", mapVal.DocumentPrefix); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if mapVal.NCtx != 0 || cst.HasValue(subTable, "n-ctx") {
				if err := cst.SetAny(subTable, "n-ctx", mapVal.NCtx); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if mapVal.Pooling != "" || cst.HasValue(subTable, "pooling") {
				if err := cst.SetAny(subTable, "pooling", mapVal.Pooling); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if mapVal.Truncate != false || cst.HasValue(subTable, "truncate") {
				if err := cst.SetAny(subTable, "truncate", mapVal.Truncate); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.Manpath != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "manpath")
		{
			if d.data.Manpath.Include != nil {
				if err := cst.SetAny(tableNode, "include", d.data.Manpath.Include); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		if d.data.Manpath.NoAuto != false || cst.HasValue(tableNode, "no-auto") {
			if err := cst.SetAny(tableNode, "no-auto", d.data.Manpath.NoAuto); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Storage != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "storage")
		if d.data.Storage.StoreID != "" || cst.HasValue(tableNode, "store-id") {
			if err := cst.SetAny(tableNode, "store-id", d.data.Storage.StoreID); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		{
			if d.data.Storage.ReadCmd != nil {
				if err := cst.SetAny(tableNode, "read-cmd", d.data.Storage.ReadCmd); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		{
			if d.data.Storage.WriteCmd != nil {
				if err := cst.SetAny(tableNode, "write-cmd", d.data.Storage.WriteCmd); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		{
			if d.data.Storage.ExistsCmd != nil {
				if err := cst.SetAny(tableNode, "exists-cmd", d.data.Storage.ExistsCmd); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		{
			if d.data.Storage.InitCmd != nil {
				if err := cst.SetAny(tableNode, "init-cmd", d.data.Storage.InitCmd); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	{
		for i := range d.data.Corpora {
			var container *cst.Node
			if i < len(d.corpora) {
				container = d.corpora[i].node
			} else {
				container = cst.AppendArrayTableEntryAfter(d.cstDoc.Root(), "corpora")
			}
			if d.data.Corpora[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", d.data.Corpora[i].Name); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Corpora[i].Type != "" || cst.HasValue(container, "type") {
				if err := cst.SetAny(container, "type", d.data.Corpora[i].Type); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				if d.data.Corpora[i].Paths != nil {
					if err := cst.SetAny(container, "paths", d.data.Corpora[i].Paths); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Corpora[i].MaxChars != 0 || cst.HasValue(container, "max-chars") {
				if err := cst.SetAny(container, "max-chars", d.data.Corpora[i].MaxChars); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			{
				if d.data.Corpora[i].ListCmd != nil {
					if err := cst.SetAny(container, "list-cmd", d.data.Corpora[i].ListCmd); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			{
				if d.data.Corpora[i].ReadCmd != nil {
					if err := cst.SetAny(container, "read-cmd", d.data.Corpora[i].ReadCmd); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			{
				if d.data.Corpora[i].HashCmd != nil {
					if err := cst.SetAny(container, "hash-cmd", d.data.Corpora[i].HashCmd); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			{
				if d.data.Corpora[i].PrepareCmd != nil {
					if err := cst.SetAny(container, "prepare-cmd", d.data.Corpora[i].PrepareCmd); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Corpora[i].Workers != 0 || cst.HasValue(container, "workers") {
				if err := cst.SetAny(container, "workers", d.data.Corpora[i].Workers); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Corpora[i].Model != "" || cst.HasValue(container, "model") {
				if err := cst.SetAny(container, "model", d.data.Corpora[i].Model); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *ManeaterConfigDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *ManeaterConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ManeaterConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ManeaterConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ManeaterConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeManeaterConfigInto(data *ManeaterConfig, sub *cst.Value) error {
	if _vDefault, _ok := sub.Get("default"); _ok && _vDefault.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDefault.Leaf); _xok {
			data.Default = _x
			_vDefault.MarkConsumed()
		}
	}
	if _vModels, _ok := sub.Get("models"); _ok && _vModels.Kind == cst.VTable {
		_vModels.MarkSeen()
		data.Models = make(map[string]ModelConfig)
		for _mk0i := range _vModels.Fields {
			_mk0e := &_vModels.Fields[_mk0i]
			if _mk0e.Val.Kind == cst.VTable {
				_mk0e.Val.MarkSeen()
				var entry1 ModelConfig
				if _vModelsPath, _ok := _mk0e.Val.Get("path"); _ok && _vModelsPath.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vModelsPath.Leaf); _xok {
						entry1.Path = _x
						_vModelsPath.MarkConsumed()
					}
				}
				if _vModelsQueryPrefix, _ok := _mk0e.Val.Get("query-prefix"); _ok && _vModelsQueryPrefix.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vModelsQueryPrefix.Leaf); _xok {
						entry1.QueryPrefix = _x
						_vModelsQueryPrefix.MarkConsumed()
					}
				}
				if _vModelsDocumentPrefix, _ok := _mk0e.Val.Get("document-prefix"); _ok && _vModelsDocumentPrefix.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vModelsDocumentPrefix.Leaf); _xok {
						entry1.DocumentPrefix = _x
						_vModelsDocumentPrefix.MarkConsumed()
					}
				}
				if _vModelsNCtx, _ok := _mk0e.Val.Get("n-ctx"); _ok && _vModelsNCtx.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractInt(_vModelsNCtx.Leaf); _xok {
						entry1.NCtx = _x
						_vModelsNCtx.MarkConsumed()
					}
				}
				if _vModelsPooling, _ok := _mk0e.Val.Get("pooling"); _ok && _vModelsPooling.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vModelsPooling.Leaf); _xok {
						entry1.Pooling = _x
						_vModelsPooling.MarkConsumed()
					}
				}
				if _vModelsTruncate, _ok := _mk0e.Val.Get("truncate"); _ok && _vModelsTruncate.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractBool(_vModelsTruncate.Leaf); _xok {
						entry1.Truncate = _x
						_vModelsTruncate.MarkConsumed()
					}
				}
				data.Models[_mk0e.Key] = entry1
			}
		}
	}
	if _vManpath, _ok := sub.Get("manpath"); _ok && _vManpath.Kind == cst.VTable {
		_vManpath.MarkSeen()
		manpathVal2 := &ManpathConfig{}
		if _vManpathInclude, _ok := _vManpath.Get("include"); _ok && _vManpathInclude.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vManpathInclude.Leaf); _xok {
				manpathVal2.Include = _x
				if manpathVal2.Include == nil {
					manpathVal2.Include = []string{}
				}
				_vManpathInclude.MarkConsumed()
			}
		}
		if _vManpathNoAuto, _ok := _vManpath.Get("no-auto"); _ok && _vManpathNoAuto.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vManpathNoAuto.Leaf); _xok {
				manpathVal2.NoAuto = _x
				_vManpathNoAuto.MarkConsumed()
			}
		}
		data.Manpath = manpathVal2
	} else {
		manpathVal2 := &ManpathConfig{}
		_foundManpath := false
		if _vInclude, _ok := sub.Get("include"); _ok && _vInclude.Kind == cst.VLeaf {
			_foundManpath = true
			if _x, _xok := cst.ExtractStringSlice(_vInclude.Leaf); _xok {
				manpathVal2.Include = _x
				if manpathVal2.Include == nil {
					manpathVal2.Include = []string{}
				}
				_vInclude.MarkConsumed()
			}
		}
		if _vNoAuto, _ok := sub.Get("no-auto"); _ok && _vNoAuto.Kind == cst.VLeaf {
			_foundManpath = true
			if _x, _xok := cst.ExtractBool(_vNoAuto.Leaf); _xok {
				manpathVal2.NoAuto = _x
				_vNoAuto.MarkConsumed()
			}
		}
		if _foundManpath {
			data.Manpath = manpathVal2
		}
	}
	if _vStorage, _ok := sub.Get("storage"); _ok && _vStorage.Kind == cst.VTable {
		_vStorage.MarkSeen()
		storageVal3 := &StorageConfig{}
		if _vStorageStoreId, _ok := _vStorage.Get("store-id"); _ok && _vStorageStoreId.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vStorageStoreId.Leaf); _xok {
				storageVal3.StoreID = _x
				_vStorageStoreId.MarkConsumed()
			}
		}
		if _vStorageReadCmd, _ok := _vStorage.Get("read-cmd"); _ok && _vStorageReadCmd.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vStorageReadCmd.Leaf); _xok {
				storageVal3.ReadCmd = _x
				if storageVal3.ReadCmd == nil {
					storageVal3.ReadCmd = []string{}
				}
				_vStorageReadCmd.MarkConsumed()
			}
		}
		if _vStorageWriteCmd, _ok := _vStorage.Get("write-cmd"); _ok && _vStorageWriteCmd.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vStorageWriteCmd.Leaf); _xok {
				storageVal3.WriteCmd = _x
				if storageVal3.WriteCmd == nil {
					storageVal3.WriteCmd = []string{}
				}
				_vStorageWriteCmd.MarkConsumed()
			}
		}
		if _vStorageExistsCmd, _ok := _vStorage.Get("exists-cmd"); _ok && _vStorageExistsCmd.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vStorageExistsCmd.Leaf); _xok {
				storageVal3.ExistsCmd = _x
				if storageVal3.ExistsCmd == nil {
					storageVal3.ExistsCmd = []string{}
				}
				_vStorageExistsCmd.MarkConsumed()
			}
		}
		if _vStorageInitCmd, _ok := _vStorage.Get("init-cmd"); _ok && _vStorageInitCmd.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractStringSlice(_vStorageInitCmd.Leaf); _xok {
				storageVal3.InitCmd = _x
				if storageVal3.InitCmd == nil {
					storageVal3.InitCmd = []string{}
				}
				_vStorageInitCmd.MarkConsumed()
			}
		}
		data.Storage = storageVal3
	} else {
		storageVal3 := &StorageConfig{}
		_foundStorage := false
		if _vStoreId, _ok := sub.Get("store-id"); _ok && _vStoreId.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractString(_vStoreId.Leaf); _xok {
				storageVal3.StoreID = _x
				_vStoreId.MarkConsumed()
			}
		}
		if _vReadCmd, _ok := sub.Get("read-cmd"); _ok && _vReadCmd.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractStringSlice(_vReadCmd.Leaf); _xok {
				storageVal3.ReadCmd = _x
				if storageVal3.ReadCmd == nil {
					storageVal3.ReadCmd = []string{}
				}
				_vReadCmd.MarkConsumed()
			}
		}
		if _vWriteCmd, _ok := sub.Get("write-cmd"); _ok && _vWriteCmd.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractStringSlice(_vWriteCmd.Leaf); _xok {
				storageVal3.WriteCmd = _x
				if storageVal3.WriteCmd == nil {
					storageVal3.WriteCmd = []string{}
				}
				_vWriteCmd.MarkConsumed()
			}
		}
		if _vExistsCmd, _ok := sub.Get("exists-cmd"); _ok && _vExistsCmd.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractStringSlice(_vExistsCmd.Leaf); _xok {
				storageVal3.ExistsCmd = _x
				if storageVal3.ExistsCmd == nil {
					storageVal3.ExistsCmd = []string{}
				}
				_vExistsCmd.MarkConsumed()
			}
		}
		if _vInitCmd, _ok := sub.Get("init-cmd"); _ok && _vInitCmd.Kind == cst.VLeaf {
			_foundStorage = true
			if _x, _xok := cst.ExtractStringSlice(_vInitCmd.Leaf); _xok {
				storageVal3.InitCmd = _x
				if storageVal3.InitCmd == nil {
					storageVal3.InitCmd = []string{}
				}
				_vInitCmd.MarkConsumed()
			}
		}
		if _foundStorage {
			data.Storage = storageVal3
		}
	}
	if _vCorpora, _ok := sub.Get("corpora"); _ok && _vCorpora.Kind == cst.VArray {
		_vCorpora.MarkSeen()
		data.Corpora = make([]CorpusConfig, len(_vCorpora.Items))
		for i := range _vCorpora.Items {
			_eCorpora := &_vCorpora.Items[i]
			_eCorpora.MarkSeen()
			if _vCorporaName, _ok := _eCorpora.Get("name"); _ok && _vCorporaName.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vCorporaName.Leaf); _xok {
					data.Corpora[i].Name = _x
					_vCorporaName.MarkConsumed()
				}
			}
			if _vCorporaType, _ok := _eCorpora.Get("type"); _ok && _vCorporaType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vCorporaType.Leaf); _xok {
					data.Corpora[i].Type = _x
					_vCorporaType.MarkConsumed()
				}
			}
			if _vCorporaPaths, _ok := _eCorpora.Get("paths"); _ok && _vCorporaPaths.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaPaths.Leaf); _xok {
					data.Corpora[i].Paths = _x
					if data.Corpora[i].Paths == nil {
						data.Corpora[i].Paths = []string{}
					}
					_vCorporaPaths.MarkConsumed()
				}
			}
			if _vCorporaMaxChars, _ok := _eCorpora.Get("max-chars"); _ok && _vCorporaMaxChars.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vCorporaMaxChars.Leaf); _xok {
					data.Corpora[i].MaxChars = _x
					_vCorporaMaxChars.MarkConsumed()
				}
			}
			if _vCorporaListCmd, _ok := _eCorpora.Get("list-cmd"); _ok && _vCorporaListCmd.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaListCmd.Leaf); _xok {
					data.Corpora[i].ListCmd = _x
					if data.Corpora[i].ListCmd == nil {
						data.Corpora[i].ListCmd = []string{}
					}
					_vCorporaListCmd.MarkConsumed()
				}
			}
			if _vCorporaReadCmd, _ok := _eCorpora.Get("read-cmd"); _ok && _vCorporaReadCmd.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaReadCmd.Leaf); _xok {
					data.Corpora[i].ReadCmd = _x
					if data.Corpora[i].ReadCmd == nil {
						data.Corpora[i].ReadCmd = []string{}
					}
					_vCorporaReadCmd.MarkConsumed()
				}
			}
			if _vCorporaHashCmd, _ok := _eCorpora.Get("hash-cmd"); _ok && _vCorporaHashCmd.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaHashCmd.Leaf); _xok {
					data.Corpora[i].HashCmd = _x
					if data.Corpora[i].HashCmd == nil {
						data.Corpora[i].HashCmd = []string{}
					}
					_vCorporaHashCmd.MarkConsumed()
				}
			}
			if _vCorporaPrepareCmd, _ok := _eCorpora.Get("prepare-cmd"); _ok && _vCorporaPrepareCmd.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractStringSlice(_vCorporaPrepareCmd.Leaf); _xok {
					data.Corpora[i].PrepareCmd = _x
					if data.Corpora[i].PrepareCmd == nil {
						data.Corpora[i].PrepareCmd = []string{}
					}
					_vCorporaPrepareCmd.MarkConsumed()
				}
			}
			if _vCorporaWorkers, _ok := _eCorpora.Get("workers"); _ok && _vCorporaWorkers.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vCorporaWorkers.Leaf); _xok {
					data.Corpora[i].Workers = _x
					_vCorporaWorkers.MarkConsumed()
				}
			}
			if _vCorporaModel, _ok := _eCorpora.Get("model"); _ok && _vCorporaModel.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vCorporaModel.Leaf); _xok {
					data.Corpora[i].Model = _x
					_vCorporaModel.MarkConsumed()
				}
			}
		}
	}
	if _eaCorpora, _eaok := sub.Get("corpora"); _eaok && _eaCorpora.IsEmptyArray() {
		_eaCorpora.MarkConsumed()
		data.Corpora = []CorpusConfig{}
	}
	return nil
}

func EncodeManeaterConfigFrom(data *ManeaterConfig, doc *document.Document, container *cst.Node) error {
	if data.Default != "" || cst.HasValue(container, "default") {
		if err := cst.SetAny(container, "default", data.Default); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if len(data.Models) > 0 {
		for mapKey, mapVal := range data.Models {
			subTable := cst.EnsureChildSubTable(doc.Root(), container, "models", mapKey)
			if mapVal.Path != "" || cst.HasValue(subTable, "path") {
				if err := cst.SetAny(subTable, "path", mapVal.Path); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if mapVal.QueryPrefix != "" || cst.HasValue(subTable, "query-prefix") {
				if err := cst.SetAny(subTable, "query-prefix", mapVal.QueryPrefix); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if mapVal.DocumentPrefix != "" || cst.HasValue(subTable, "document-prefix") {
				if err := cst.SetAny(subTable, "document-prefix", mapVal.DocumentPrefix); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if mapVal.NCtx != 0 || cst.HasValue(subTable, "n-ctx") {
				if err := cst.SetAny(subTable, "n-ctx", mapVal.NCtx); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if mapVal.Pooling != "" || cst.HasValue(subTable, "pooling") {
				if err := cst.SetAny(subTable, "pooling", mapVal.Pooling); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if mapVal.Truncate != false || cst.HasValue(subTable, "truncate") {
				if err := cst.SetAny(subTable, "truncate", mapVal.Truncate); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.Manpath != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "manpath")
		{
			if data.Manpath.Include != nil {
				if err := cst.SetAny(tableNode, "include", data.Manpath.Include); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		if data.Manpath.NoAuto != false || cst.HasValue(tableNode, "no-auto") {
			if err := cst.SetAny(tableNode, "no-auto", data.Manpath.NoAuto); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Storage != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "storage")
		if data.Storage.StoreID != "" || cst.HasValue(tableNode, "store-id") {
			if err := cst.SetAny(tableNode, "store-id", data.Storage.StoreID); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		{
			if data.Storage.ReadCmd != nil {
				if err := cst.SetAny(tableNode, "read-cmd", data.Storage.ReadCmd); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		{
			if data.Storage.WriteCmd != nil {
				if err := cst.SetAny(tableNode, "write-cmd", data.Storage.WriteCmd); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		{
			if data.Storage.ExistsCmd != nil {
				if err := cst.SetAny(tableNode, "exists-cmd", data.Storage.ExistsCmd); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		{
			if data.Storage.InitCmd != nil {
				if err := cst.SetAny(tableNode, "init-cmd", data.Storage.InitCmd); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	{
		_apCorpora := container
		_existCorpora := cst.FindChildArrayTableNodes(doc.Root(), _apCorpora, "corpora")
		for i := range data.Corpora {
			var container *cst.Node
			if i < len(_existCorpora) {
				container = _existCorpora[i]
			} else {
				container = cst.AppendChildArrayTableEntry(doc.Root(), _apCorpora, "corpora")
			}
			if data.Corpora[i].Name != "" || cst.HasValue(container, "name") {
				if err := cst.SetAny(container, "name", data.Corpora[i].Name); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Corpora[i].Type != "" || cst.HasValue(container, "type") {
				if err := cst.SetAny(container, "type", data.Corpora[i].Type); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				if data.Corpora[i].Paths != nil {
					if err := cst.SetAny(container, "paths", data.Corpora[i].Paths); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Corpora[i].MaxChars != 0 || cst.HasValue(container, "max-chars") {
				if err := cst.SetAny(container, "max-chars", data.Corpora[i].MaxChars); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			{
				if data.Corpora[i].ListCmd != nil {
					if err := cst.SetAny(container, "list-cmd", data.Corpora[i].ListCmd); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			{
				if data.Corpora[i].ReadCmd != nil {
					if err := cst.SetAny(container, "read-cmd", data.Corpora[i].ReadCmd); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			{
				if data.Corpora[i].HashCmd != nil {
					if err := cst.SetAny(container, "hash-cmd", data.Corpora[i].HashCmd); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			{
				if data.Corpora[i].PrepareCmd != nil {
					if err := cst.SetAny(container, "prepare-cmd", data.Corpora[i].PrepareCmd); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Corpora[i].Workers != 0 || cst.HasValue(container, "workers") {
				if err := cst.SetAny(container, "workers", data.Corpora[i].Workers); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Corpora[i].Model != "" || cst.HasValue(container, "model") {
				if err := cst.SetAny(container, "model", data.Corpora[i].Model); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	return nil
}
