// Code generated by tommy; DO NOT EDIT.

package config

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type ManeaterConfigDocument struct {
	data     ManeaterConfig
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeManeaterConfig(input []byte) (*ManeaterConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &ManeaterConfigDocument{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "default":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Default = v
				d.consumed["default"] = true
			}
		}
	}
	{
		var _mr map[string]ModelConfig
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind != cst.NodeTable {
				continue
			}
			_hdr := cst.TableHeaderKey(_ch)
			if !strings.HasPrefix(_hdr, "models.") {
				continue
			}
			_mk := _hdr[7:]
			if strings.Contains(_mk, ".") {
				continue
			}
			if _mr == nil {
				d.consumed["models"] = true
				_mr = make(map[string]ModelConfig)
			}
			d.consumed["models"+"."+_mk] = true
			var entry ModelConfig
			for _, _kv := range _ch.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "path":
					if v, ok := cst.ExtractString(_kv); ok {
						entry.Path = v
						d.consumed["models."+_mk+"."+"path"] = true
					}
				case "query-prefix":
					if v, ok := cst.ExtractString(_kv); ok {
						entry.QueryPrefix = v
						d.consumed["models."+_mk+"."+"query-prefix"] = true
					}
				case "document-prefix":
					if v, ok := cst.ExtractString(_kv); ok {
						entry.DocumentPrefix = v
						d.consumed["models."+_mk+"."+"document-prefix"] = true
					}
				}
			}
			_mr[_mk] = entry
		}
		if _mr != nil {
			d.data.Models = _mr
		}
	}
	{
		var _ftManpath *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "manpath" {
				_ftManpath = _ch
				break
			}
		}
		if _ftManpath != nil {
			d.consumed["manpath"] = true
			manpathVal := &ManpathConfig{}
			for _, _kv := range _ftManpath.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "include":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						manpathVal.Include = v
						d.consumed["manpath.include"] = true
					}
				case "no-auto":
					if v, ok := cst.ExtractBool(_kv); ok {
						manpathVal.NoAuto = v
						d.consumed["manpath.no-auto"] = true
					}
				}
			}
			d.data.Manpath = manpathVal
		} else {
			manpathVal := &ManpathConfig{}
			_found := false
			for _, _kv := range d.cstDoc.Root().Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "include":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						manpathVal.Include = v
						d.consumed["include"] = true
					}
				case "no-auto":
					if v, ok := cst.ExtractBool(_kv); ok {
						manpathVal.NoAuto = v
						_found = true
						d.consumed["no-auto"] = true
					}
				}
			}
			if _found {
				d.data.Manpath = manpathVal
			}
		}
	}
	{
		var _ftStorage *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "storage" {
				_ftStorage = _ch
				break
			}
		}
		if _ftStorage != nil {
			d.consumed["storage"] = true
			storageVal := &StorageConfig{}
			for _, _kv := range _ftStorage.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "store-id":
					if v, ok := cst.ExtractString(_kv); ok {
						storageVal.StoreID = v
						d.consumed["storage.store-id"] = true
					}
				}
			}
			d.data.Storage = storageVal
		} else {
			storageVal := &StorageConfig{}
			_found := false
			for _, _kv := range d.cstDoc.Root().Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "store-id":
					if v, ok := cst.ExtractString(_kv); ok {
						storageVal.StoreID = v
						_found = true
						d.consumed["store-id"] = true
					}
				}
			}
			if _found {
				d.data.Storage = storageVal
			}
		}
	}
	return d, nil
}
func (d *ManeaterConfigDocument) Data() *ManeaterConfig {
	return &d.data
}
func (d *ManeaterConfigDocument) Encode() ([]byte, error) {
	if d.data.Default != "" || cst.HasValue(d.cstDoc.Root(), "default") {
		if err := cst.SetAny(d.cstDoc.Root(), "default", d.data.Default); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if len(d.data.Models) > 0 {
		for mapKey, mapVal := range d.data.Models {
			subTable := cst.EnsureChildSubTable(d.cstDoc.Root(), d.cstDoc.Root(), "models", mapKey)
			if mapVal.Path != "" || cst.HasValue(subTable, "path") {
				if err := cst.SetAny(subTable, "path", mapVal.Path); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if mapVal.QueryPrefix != "" || cst.HasValue(subTable, "query-prefix") {
				if err := cst.SetAny(subTable, "query-prefix", mapVal.QueryPrefix); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if mapVal.DocumentPrefix != "" || cst.HasValue(subTable, "document-prefix") {
				if err := cst.SetAny(subTable, "document-prefix", mapVal.DocumentPrefix); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.Manpath != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "manpath")
		{
			if err := cst.SetAny(tableNode, "include", d.data.Manpath.Include); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Manpath.NoAuto != false || cst.HasValue(tableNode, "no-auto") {
			if err := cst.SetAny(tableNode, "no-auto", d.data.Manpath.NoAuto); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Storage != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "storage")
		if d.data.Storage.StoreID != "" || cst.HasValue(tableNode, "store-id") {
			if err := cst.SetAny(tableNode, "store-id", d.data.Storage.StoreID); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *ManeaterConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *ManeaterConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *ManeaterConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *ManeaterConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *ManeaterConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeManeaterConfigInto(data *ManeaterConfig, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "default":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Default = v
				consumed[keyPrefix+"default"] = true
			}
		}
	}
	{
		var _mr map[string]ModelConfig
		for _, _ch := range doc.Root().Children {
			if _ch.Kind != cst.NodeTable {
				continue
			}
			_hdr := cst.TableHeaderKey(_ch)
			if !strings.HasPrefix(_hdr, keyPrefix+"models.") {
				continue
			}
			_mk := _hdr[len(keyPrefix)+len("models."):]
			if strings.Contains(_mk, ".") {
				continue
			}
			if _mr == nil {
				consumed[keyPrefix+"models"] = true
				_mr = make(map[string]ModelConfig)
			}
			consumed[keyPrefix+"models"+"."+_mk] = true
			var entry ModelConfig
			for _, _kv := range _ch.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "path":
					if v, ok := cst.ExtractString(_kv); ok {
						entry.Path = v
						consumed[keyPrefix+keyPrefix+"models."+_mk+"."+"path"] = true
					}
				case "query-prefix":
					if v, ok := cst.ExtractString(_kv); ok {
						entry.QueryPrefix = v
						consumed[keyPrefix+keyPrefix+"models."+_mk+"."+"query-prefix"] = true
					}
				case "document-prefix":
					if v, ok := cst.ExtractString(_kv); ok {
						entry.DocumentPrefix = v
						consumed[keyPrefix+keyPrefix+"models."+_mk+"."+"document-prefix"] = true
					}
				}
			}
			_mr[_mk] = entry
		}
		if _mr != nil {
			data.Models = _mr
		}
	}
	{
		var _ftManpath *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"manpath" {
				_ftManpath = _ch
				break
			}
		}
		if _ftManpath != nil {
			consumed[keyPrefix+"manpath"] = true
			manpathVal := &ManpathConfig{}
			for _, _kv := range _ftManpath.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "include":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						manpathVal.Include = v
						consumed[keyPrefix+"manpath.include"] = true
					}
				case "no-auto":
					if v, ok := cst.ExtractBool(_kv); ok {
						manpathVal.NoAuto = v
						consumed[keyPrefix+"manpath.no-auto"] = true
					}
				}
			}
			data.Manpath = manpathVal
		} else {
			manpathVal := &ManpathConfig{}
			_found := false
			for _, _kv := range container.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "include":
					if v, ok := cst.ExtractStringSlice(_kv); ok {
						manpathVal.Include = v
						consumed["include"] = true
					}
				case "no-auto":
					if v, ok := cst.ExtractBool(_kv); ok {
						manpathVal.NoAuto = v
						_found = true
						consumed["no-auto"] = true
					}
				}
			}
			if _found {
				data.Manpath = manpathVal
			}
		}
	}
	{
		var _ftStorage *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"storage" {
				_ftStorage = _ch
				break
			}
		}
		if _ftStorage != nil {
			consumed[keyPrefix+"storage"] = true
			storageVal := &StorageConfig{}
			for _, _kv := range _ftStorage.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "store-id":
					if v, ok := cst.ExtractString(_kv); ok {
						storageVal.StoreID = v
						consumed[keyPrefix+"storage.store-id"] = true
					}
				}
			}
			data.Storage = storageVal
		} else {
			storageVal := &StorageConfig{}
			_found := false
			for _, _kv := range container.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "store-id":
					if v, ok := cst.ExtractString(_kv); ok {
						storageVal.StoreID = v
						_found = true
						consumed["store-id"] = true
					}
				}
			}
			if _found {
				data.Storage = storageVal
			}
		}
	}
	return nil
}
func EncodeManeaterConfigFrom(data *ManeaterConfig, doc *document.Document, container *cst.Node) error {
	if data.Default != "" || cst.HasValue(container, "default") {
		if err := cst.SetAny(container, "default", data.Default); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if len(data.Models) > 0 {
		for mapKey, mapVal := range data.Models {
			subTable := cst.EnsureChildSubTable(doc.Root(), container, "models", mapKey)
			if mapVal.Path != "" || cst.HasValue(subTable, "path") {
				if err := cst.SetAny(subTable, "path", mapVal.Path); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if mapVal.QueryPrefix != "" || cst.HasValue(subTable, "query-prefix") {
				if err := cst.SetAny(subTable, "query-prefix", mapVal.QueryPrefix); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if mapVal.DocumentPrefix != "" || cst.HasValue(subTable, "document-prefix") {
				if err := cst.SetAny(subTable, "document-prefix", mapVal.DocumentPrefix); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.Manpath != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "manpath")
		{
			if err := cst.SetAny(tableNode, "include", data.Manpath.Include); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Manpath.NoAuto != false || cst.HasValue(tableNode, "no-auto") {
			if err := cst.SetAny(tableNode, "no-auto", data.Manpath.NoAuto); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Storage != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "storage")
		if data.Storage.StoreID != "" || cst.HasValue(tableNode, "store-id") {
			if err := cst.SetAny(tableNode, "store-id", data.Storage.StoreID); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	return nil
}
